// Locations: approximate positions (map units) and short original summaries.
// tier: 1 = major (always labelled), 2 = notable, 3 = minor (shown when zoomed in).
export const KINDS = {
  city: 'City', town: 'Town / village', fortress: 'Fortress', elven: 'Elven realm', dwarven: 'Dwarf-realm',
  dark: 'Dark stronghold', landmark: 'Landmark', forest: 'Forest', haven: 'Haven', realm: 'Land', ruin: 'Ruin'
};

export const PLACES = [
  { id: 'bagend', name: 'Hobbiton & Bag End', x: 226, y: 262, tier: 1, kind: 'town', region: 'The Shire · Westfarthing',
    what: 'Hobbit village on the Water; Bag End is the finest hole dug into the Hill above it.',
    history: 'Bungo Baggins dug Bag End into the Hill for his bride, Belladonna Took. Their son Bilbo left its round green door on the adventure told in The Hobbit, and sixty years later vanished from his own birthday party. Frodo inherited the house and the Ring, and the Quest quietly began here. After the war Sam Gamgee raised his large family in Bag End.' },
  { id: 'bywater', name: 'Bywater', x: 241, y: 269, tier: 3, kind: 'town', region: 'The Shire',
    what: 'Village beside a pool on the East Road, home of the Green Dragon inn.',
    history: 'Bywater was a short walk from Hobbiton, and the Green Dragon was a favourite evening haunt of Sam and his friends. In November 3019 it gave its name to the Battle of Bywater, the last fight of the War of the Ring, when the hobbits rose up under Merry and Pippin and routed the ruffians who had taken over the Shire.' },
  { id: 'micheldelving', name: 'Michel Delving', x: 197, y: 276, tier: 3, kind: 'town', region: 'The Shire · White Downs',
    what: 'Chief township of the Shire and seat of its Mayor.',
    history: 'Michel Delving stands on the White Downs in the Westfarthing. It housed the Mathom-house, where hobbits kept curious things they could neither use nor bear to throw away, including for a time Bilbo\u2019s mithril coat. Sam Gamgee was later elected Mayor here for seven terms in a row.' },
  { id: 'buckland', name: 'Buckland & Crickhollow', x: 296, y: 272, tier: 2, kind: 'town', region: 'Buckland, east of the Brandywine',
    what: 'Hedged hobbit country across the river, ruled by the Master of Brandy Hall.',
    history: 'The Oldbuck family crossed the Brandywine, took the name Brandybuck and burrowed Brandy Hall into Buck Hill; the High Hay hedge protects the land from the Old Forest. Frodo pretended to settle at a little house in Crickhollow, where Merry and Pippin revealed they knew about the Ring and insisted on coming. Black Riders burst into the house the night after the hobbits had left.' },
  { id: 'oldforest', name: 'Old Forest & Bombadil\u2019s House', x: 315, y: 277, tier: 2, kind: 'forest', region: 'Eriador, east of Buckland',
    what: 'A brooding remnant of the primeval woods, and the home of Tom Bombadil.',
    history: 'The Old Forest is one of the last survivors of the great woods that once covered Eriador, and its trees remember every axe and fire. By the Withywindle, Old Man Willow swallowed Merry and Pippin into his trunk until Tom Bombadil sang him into letting go. Tom and Goldberry sheltered the hobbits in their house at the forest\u2019s edge; the Ring had no hold over Tom at all.' },
  { id: 'barrowdowns', name: 'Barrow-downs', x: 330, y: 301, tier: 3, kind: 'landmark', region: 'Eriador',
    what: 'Grassy hills crowned with ancient burial mounds.',
    history: 'Long ago the Edain, and later princes of the northern kingdom, were buried in barrows on these downs. After the wars with Angmar evil spirits, the Barrow-wights, came to dwell in the tombs. A wight trapped Frodo and his friends in the fog until Tom Bombadil broke the barrow open. From its hoard the hobbits took old daggers of Westernesse, and Merry\u2019s later helped bring down the Witch-king.' },
  { id: 'bree', name: 'Bree', x: 350, y: 268, tier: 1, kind: 'town', region: 'Bree-land',
    what: 'Crossroads village where Men and hobbits lived side by side.',
    history: 'Bree grew up where the East Road met the old North-South Road, and its inn, the Prancing Pony, collected news from every direction. There Frodo accidentally slipped on the Ring during a song and first met the Ranger called Strider. Barliman Butterbur finally handed over Gandalf\u2019s long-forgotten letter, and the hobbits\u2019 empty rooms were attacked in the night before Strider led them east into the Wild.' },
  { id: 'weathertop', name: 'Weathertop', alt: 'Amon Sûl', x: 431, y: 262, tier: 2, kind: 'ruin', region: 'Weather Hills · old Arnor',
    what: 'A bare hilltop crowned by the ruins of an ancient watchtower.',
    history: 'The great tower of Amon Sûl once stood here and held the chief seeing-stone of the North, until it was burned in the wars with Angmar. Only a broken ring of stones remained by the end of the Third Age. Gandalf fought the Nazgûl on the summit a few nights before Frodo\u2019s party arrived, and in the dell below the Witch-king wounded Frodo with a Morgul-knife.' },
  { id: 'trollshaws', name: 'Trollshaws', x: 524, y: 248, tier: 3, kind: 'forest', region: 'Rhudaur, between Hoarwell and Loudwater',
    what: 'Wooded hills where three trolls were famously turned to stone.',
    history: 'Bilbo\u2019s clumsy attempt at burglary here got the whole company caught by three trolls, Bert, Tom and William. Gandalf kept them arguing until dawn turned them to stone. In the trolls\u2019 cave were found Glamdring, Orcrist and the little blade Bilbo later named Sting. Frodo\u2019s party passed the stone trolls on their way to Rivendell.' },
  { id: 'rivendell', name: 'Rivendell', alt: 'Imladris', x: 582, y: 246, tier: 1, kind: 'elven', region: 'Eriador, under the Misty Mountains',
    what: 'Elrond\u2019s hidden valley: the Last Homely House east of the Sea.',
    history: 'Elrond Half-elven founded Rivendell in the Second Age as a refuge during the war against Sauron, and it endured as a house of healing, lore and song. Bilbo rested here on both legs of his adventure and later retired here to write. Frodo was healed of his Morgul wound in its halls, the Council of Elrond decided the Ring\u2019s fate, and the Fellowship set out from here in midwinter.' },
  { id: 'greyhavens', name: 'Grey Havens', alt: 'Mithlond', x: 133, y: 252, tier: 1, kind: 'haven', region: 'Lindon, Gulf of Lune',
    what: 'The Elves\u2019 harbour from which ships sail into the West.',
    history: 'Círdan the Shipwright ruled the havens at the head of the Gulf of Lune and built the white ships that carried weary Elves over the Sea. It was here that Círdan gave Gandalf the Ring of Fire when the wizard first arrived. In 3021 Frodo and Bilbo, with Gandalf, Elrond and Galadriel, took the last ship of the Ring-bearers while Sam, Merry and Pippin watched from the quay.' },
  { id: 'thorinshalls', name: 'Thorin\u2019s Halls', x: 154, y: 196, tier: 3, kind: 'dwarven', region: 'Ered Luin (Blue Mountains)',
    what: 'Mines and halls of Durin\u2019s exiled folk.',
    history: 'After the dragon took Erebor and the war against the Orcs of Moria, Thráin and his son Thorin settled with their people in the Blue Mountains, working iron and trading with Men and hobbits. From here Thorin set out on the quest that brought him to Bilbo\u2019s door.' },
  { id: 'annuminas', name: 'Annúminas', x: 222, y: 168, tier: 3, kind: 'ruin', region: 'Arnor · Lake Evendim',
    what: 'Ancient lakeside capital of the North-kingdom.',
    history: 'Elendil built Annúminas on the shore of Lake Evendim as the first capital of Arnor after the Downfall of Númenor. As the kingdom shrank the kings moved to Fornost and the city decayed into ruin. In the Fourth Age King Elessar rebuilt it and at times held court there.' },
  { id: 'fornost', name: 'Fornost', alt: 'Norbury of the Kings', x: 338, y: 196, tier: 3, kind: 'ruin', region: 'North Downs',
    what: 'Ruined fortress-city of the last northern kings.',
    history: 'Fornost was the stronghold of Arthedain, last of the northern realms. The Witch-king of Angmar captured it in 1974 of the Third Age, and the next year an alliance of Gondor, Lindon and Rivendell routed him nearby; Glorfindel then foretold that he would not fall by the hand of man. Hobbits later called the haunted ruins Deadmen\u2019s Dike.' },
  { id: 'ettenmoors', name: 'Ettenmoors', x: 556, y: 178, tier: 3, kind: 'landmark', region: 'Rhudaur',
    what: 'Bleak, troll-haunted uplands north of Rivendell.',
    history: 'The Hoarwell rises among these desolate moors, where trolls hunted and the sons of Elrond rode against them. Aragorn and the hobbits skirted their southern edge on the way to the Ford of Bruinen.' },
  { id: 'tharbad', name: 'Tharbad', x: 440, y: 410, tier: 3, kind: 'ruin', region: 'Minhiriath / Enedwaith',
    what: 'Abandoned river-town at an old bridge over the Greyflood.',
    history: 'Gondor and Arnor once kept a fortified bridge and river-port here where the North-South Road crossed the Greyflood. Floods and the emptying of Eriador left only crumbling causeways in a marsh. Boromir lost his horse at the broken crossing during his long ride north to Rivendell.' },
  { id: 'hollin', name: 'Hollin', alt: 'Eregion', x: 542, y: 362, tier: 3, kind: 'ruin', region: 'Eriador, west of Moria',
    what: 'Empty land of holly-trees, once the realm of the Elven-smiths.',
    history: 'In the Second Age the Noldorin smiths of Eregion, led by Celebrimbor, befriended the Dwarves of Moria and, tricked by Sauron in a fair disguise, forged the Rings of Power. When his deceit was revealed Sauron laid the land waste. The Fellowship rested here and hid from flocks of spying crebain before turning to the mountains.' },
  { id: 'caradhras', name: 'Caradhras', alt: 'The Redhorn', x: 608, y: 383, tier: 2, kind: 'landmark', region: 'Misty Mountains',
    what: 'Red-sided peak above the Redhorn Pass.',
    history: 'Caradhras is the greatest of the three peaks over Moria, called Barazinbar by the Dwarves. The Fellowship tried to cross the Redhorn Pass in winter, but a blinding storm that seemed to come from the mountain\u2019s own malice buried the path, and they were forced back down toward the Mines.' },
  { id: 'moria', name: 'Moria', alt: 'Khazad-dûm', x: 603, y: 404, tier: 1, kind: 'dwarven', region: 'Beneath the Misty Mountains',
    what: 'The vast, abandoned dwarf-city under the mountains.',
    history: 'Durin\u2019s folk delved Khazad-dûm over many ages and grew rich on mithril. In 1980 of the Third Age they dug too deep and woke a Balrog, and the realm was abandoned; Balin\u2019s later attempt to reclaim it ended with his colony\u2019s destruction. The Fellowship crossed it in darkness, and on the Bridge of Khazad-dûm Gandalf held off the Balrog and fell with it into the abyss.' },
  { id: 'lorien', name: 'Lothlórien', alt: 'Caras Galadhon', x: 667, y: 452, tier: 1, kind: 'elven', region: 'Between the Silverlode and the Anduin',
    what: 'The Golden Wood and its city of tree-dwellings.',
    history: 'Lothlórien is a realm of silver-barked, golden-leaved mallorn trees, preserved by the power of Galadriel\u2019s ring. Galadriel and Celeborn dwelt on a hill-city of platforms in the great trees, Caras Galadhon. The grieving Fellowship rested here after Moria; Frodo and Sam looked into the Mirror of Galadriel, and the company left with elven cloaks, lembas and grey boats.' },
  { id: 'gladden', name: 'Gladden Fields', x: 666, y: 326, tier: 3, kind: 'landmark', region: 'Vale of Anduin',
    what: 'Reedy marshes where the One Ring was lost and found.',
    history: 'Early in the Third Age Isildur was ambushed by Orcs near here; he put on the Ring and fled into the river, where it slipped from his finger and he was slain. Nearly two and a half thousand years later a river-folk hobbit named Déagol found it while fishing, and his friend Sméagol murdered him to have it.' },
  { id: 'carrock', name: 'The Carrock', x: 668, y: 237, tier: 3, kind: 'landmark', region: 'Vale of Anduin',
    what: 'A great rock in the river with steps up its side.',
    history: 'The eagles set Bilbo, Gandalf and the dwarves down on its flat top after saving them from goblins and wolves. Beorn was said to have cut its steps and to sit there at night watching the river.' },
  { id: 'beorn', name: 'Beorn\u2019s House', x: 694, y: 254, tier: 2, kind: 'town', region: 'Vale of Anduin',
    what: 'Timber hall of the bear-shaped skin-changer.',
    history: 'Beorn kept his hall among oak-woods, bee-pastures and flowers, served by his talking animals. Gandalf won him over by telling the company\u2019s story a few dwarves at a time; Beorn fed them, lent them ponies and warned them never to leave the path in Mirkwood. He came to the Battle of Five Armies as a great bear and turned the tide.' },
  { id: 'goblintown', name: 'Goblin-town & High Pass', x: 616, y: 236, tier: 3, kind: 'dark', region: 'Misty Mountains',
    what: 'Orc warrens beneath the main pass over the mountains.',
    history: 'Sheltering from a storm in a cave by the High Pass, Bilbo\u2019s company was snatched by goblins and dragged before the Great Goblin, whom Gandalf slew. Separated in the dark tunnels, Bilbo found a ring on the floor and won a game of riddles with Gollum before slipping out invisibly.' },
  { id: 'gundabad', name: 'Mount Gundabad', x: 602, y: 40, tier: 3, kind: 'dark', region: 'North end of the Misty Mountains',
    what: 'Sacred dwarf-peak turned Orc stronghold.',
    history: 'The Dwarves revere Gundabad as the place where Durin the Deathless awoke. In later ages it became a chief seat of the Orcs, and Bolg led its host south to the Battle of Five Armies.' },
  { id: 'mirkwood', name: 'Mirkwood', alt: 'Greenwood the Great', x: 792, y: 300, tier: 1, kind: 'forest', region: 'Rhovanion',
    what: 'The greatest forest of the north, dark and perilous.',
    history: 'Once called Greenwood the Great, the forest darkened after a shadow settled at Dol Guldur about a thousand years into the Third Age, and Men renamed it Mirkwood. Giant spiders, enchanted streams and endless gloom filled it. Bilbo saved the dwarves from the spiders here and named his sword Sting. After the War of the Ring it became Eryn Lasgalen, the Wood of Greenleaves.' },
  { id: 'rhosgobel', name: 'Rhosgobel', x: 707, y: 336, tier: 3, kind: 'town', region: 'Western eaves of Mirkwood',
    what: 'Home of Radagast the Brown.',
    history: 'Radagast, the wizard most devoted to birds and beasts, lived at Rhosgobel near the forest\u2019s edge. In good faith he carried Saruman\u2019s message that lured Gandalf to Orthanc, and later sent the eagle that rescued him.' },
  { id: 'thranduil', name: 'Thranduil\u2019s Halls', alt: 'The Woodland Realm', x: 842, y: 168, tier: 2, kind: 'elven', region: 'Northern Mirkwood',
    what: 'Cave-palace of the Wood-elf king, father of Legolas.',
    history: 'King Thranduil ruled the Wood-elves from a great cave beside the Forest River. Thorin\u2019s company were locked in his dungeons until Bilbo, invisible, stole the keys and floated them out in empty barrels. Gollum was later held here too, until he escaped during an Orc attack.' },
  { id: 'laketown', name: 'Lake-town', alt: 'Esgaroth', x: 905, y: 199, tier: 2, kind: 'town', region: 'Long Lake',
    what: 'A town of Men built on stilts in the Long Lake.',
    history: 'Esgaroth lived on trade between the Elves and the lands to the south, governed by its Master. It cheered Thorin\u2019s company on their way to the Mountain, and then bore the brunt of Smaug\u2019s fury. Bard the Bowman brought the dragon down with his black arrow, and the burning wreck fell upon the town; a new Lake-town was built afterwards.' },
  { id: 'dale', name: 'Dale', x: 917, y: 150, tier: 2, kind: 'city', region: 'Before the Lonely Mountain',
    what: 'Merry city of Men famous for its toys and bells.',
    history: 'Dale flourished beside the dwarves of Erebor until Smaug came in 2770 and laid it waste. After the dragon\u2019s death Bard rebuilt it and became its king. During the War of the Ring an eastern army besieged it, and King Brand and old Dáin Ironfoot fell defending the gates of the Mountain.' },
  { id: 'erebor', name: 'Erebor', alt: 'The Lonely Mountain', x: 923, y: 126, tier: 1, kind: 'dwarven', region: 'Rhovanion',
    what: 'Solitary mountain and seat of the King under the Mountain.',
    history: 'Thráin I founded a dwarf-kingdom here in 1999 of the Third Age, and under King Thrór it grew famously rich, until the dragon Smaug seized it. Thorin Oakenshield\u2019s company came to win it back with Bilbo as their burglar; Bilbo spoke with the dragon and pocketed the Arkenstone. After Smaug\u2019s death the Battle of Five Armies was fought at its feet, and Dáin became king.' },
  { id: 'ironhills', name: 'Iron Hills', x: 1052, y: 100, tier: 3, kind: 'dwarven', region: 'East of Erebor',
    what: 'Dwarf-colony rich in iron.',
    history: 'A branch of Durin\u2019s folk mined iron in these hills. Dáin Ironfoot marched their warriors to Erebor in time for the Battle of Five Armies and afterward ruled as King under the Mountain.' },
  { id: 'dolguldur', name: 'Dol Guldur', x: 727, y: 447, tier: 1, kind: 'dark', region: 'Southern Mirkwood',
    what: 'Fortress of the Necromancer on a bare hill.',
    history: 'Sauron hid here for centuries as the mysterious Necromancer while his strength returned. Gandalf crept in and discovered who he truly was, and in 2941 the White Council drove him out, only for three of the Nazgûl to reoccupy it later. During the War of the Ring its armies assailed Lórien and the Woodland Realm; afterward Galadriel threw down its walls.' },
  { id: 'fangorn', name: 'Fangorn Forest', x: 620, y: 546, tier: 1, kind: 'forest', region: 'Under the southern Misty Mountains',
    what: 'Ancient, tangled forest shepherded by the Ents.',
    history: 'Fangorn is among the oldest forests left in Middle-earth, tended by the Ents. Merry and Pippin fled into it when the Riders of Rohan attacked their Orc captors, and befriended Treebeard, eldest of the Ents. The Entmoot at Derndingle stirred the trees to march on Isengard, and in the eaves Aragorn, Legolas and Gimli met Gandalf the White.' },
  { id: 'isengard', name: 'Isengard & Orthanc', x: 576, y: 578, tier: 1, kind: 'fortress', region: 'Nan Curunír, south tip of the Misty Mountains',
    what: 'A stone ring-wall enclosing the black tower of Orthanc.',
    history: 'Gondor built Isengard and its unbreakable tower in its days of power, and later let Saruman dwell there. The wizard turned it into a smoking arsenal, bred Uruk-hai beneath it and imprisoned Gandalf on Orthanc\u2019s summit. The Ents broke the ring-wall and drowned the vale; Gandalf broke Saruman\u2019s staff, and Wormtongue hurled down the palantír.' },
  { id: 'fordsisen', name: 'Fords of Isen', x: 552, y: 613, tier: 3, kind: 'landmark', region: 'Gap of Rohan',
    what: 'The main crossing into Rohan from the west.',
    history: 'Two battles were fought here against Saruman\u2019s forces early in the War of the Ring. In the first, Théodred, the only son of King Théoden, was slain.' },
  { id: 'helmsdeep', name: 'Helm\u2019s Deep', alt: 'The Hornburg', x: 563, y: 638, tier: 1, kind: 'fortress', region: 'Rohan · Westfold',
    what: 'Mountain gorge guarded by the Deeping Wall and the Hornburg.',
    history: 'The refuge takes its name from Helm Hammerhand, who held out here through a terrible winter. On a night of storm Saruman\u2019s host assailed Théoden\u2019s men behind the Deeping Wall. At dawn Gandalf arrived with Erkenbrand\u2019s riders, and a wood of wrathful Huorns that had appeared overnight swallowed the fleeing Orcs. Gimli and Legolas kept their famous tally there.' },
  { id: 'edoras', name: 'Edoras', x: 626, y: 668, tier: 1, kind: 'city', region: 'Rohan',
    what: 'Royal town of Rohan with its golden hall, Meduseld.',
    history: 'Brego son of Eorl built Edoras on a green hill below the White Mountains, crowned by the golden-roofed hall of Meduseld. Gandalf roused King Théoden here from the poisonous counsel of Gríma Wormtongue, and the king rode to war once more. Later the host of the Rohirrim gathered here before the great ride to Gondor.' },
  { id: 'dunharrow', name: 'Dunharrow', x: 633, y: 690, tier: 3, kind: 'fortress', region: 'Rohan · Harrowdale',
    what: 'Ancient mountain refuge above Harrowdale.',
    history: 'A winding road guarded by weathered Púkel-men climbs to this ancient high meadow. The Rohirrim mustered here before riding to Minas Tirith, and here Aragorn left them to take the dark door beneath the Dwimorberg.' },
  { id: 'pathsdead', name: 'Paths of the Dead', x: 610, y: 724, tier: 3, kind: 'landmark', region: 'Under the White Mountains',
    what: 'A haunted road through the mountains.',
    history: 'The Dead who haunt this road were Men who broke their oath to Isildur and could not rest. Aragorn, as Isildur\u2019s heir, led the Grey Company through it, and the shadow host followed him to fulfil their oath at last.' },
  { id: 'erech', name: 'Stone of Erech', x: 588, y: 752, tier: 3, kind: 'landmark', region: 'Gondor · Morthond Vale',
    what: 'A black stone brought from Númenor.',
    history: 'Isildur set this stone on the hill of Erech, and the King of the Mountains swore allegiance upon it, an oath he later broke. Aragorn summoned the Dead here at midnight and led them on to Pelargir.' },
  { id: 'dolamroth', name: 'Dol Amroth', x: 612, y: 872, tier: 2, kind: 'city', region: 'Gondor · Belfalas',
    what: 'Seaside stronghold of the Princes of Dol Amroth.',
    history: 'The castle-city crowns a headland of Belfalas and is named for Amroth, an Elf-king who was lost in the bay nearby. Its princes were said to have Elvish blood. Prince Imrahil led his swan-knights to the defence of Minas Tirith and fought on the Pelennor Fields.' },
  { id: 'pelargir', name: 'Pelargir', x: 843, y: 828, tier: 2, kind: 'city', region: 'Gondor · Lebennin',
    what: 'Ancient port of Gondor on the lower Anduin.',
    history: 'The Faithful of Númenor founded Pelargir long before Gondor itself existed. In the War of the Ring the Corsairs of Umbar gathered their fleet here; Aragorn fell upon them with the Army of the Dead, captured the ships and sailed them up the Anduin to Minas Tirith.' },
  { id: 'minastirith', name: 'Minas Tirith', alt: 'Minas Anor', x: 801, y: 732, tier: 1, kind: 'city', region: 'Gondor · Anórien',
    what: 'The white city of Gondor, built in seven walled tiers.',
    history: 'First named Minas Anor, the Tower of the Sun, the city became Gondor\u2019s capital as Osgiliath decayed. Pippin served the Steward Denethor here as a guard of the Citadel. Sauron\u2019s great army besieged it, and it was saved in the Battle of the Pelennor Fields by the Rohirrim and by Aragorn\u2019s arrival with the black ships. Aragorn was crowned King Elessar before its gate.' },
  { id: 'osgiliath', name: 'Osgiliath', x: 823, y: 735, tier: 2, kind: 'ruin', region: 'Gondor, on the Anduin',
    what: 'The ruined first capital of Gondor.',
    history: 'Osgiliath spanned the Anduin with a great bridge and was crowned by the Dome of Stars. Civil war, plague and long assaults from Mordor left it in ruins. Gondor\u2019s soldiers held its crossings until the Witch-king\u2019s host forced them back to the Pelennor.' },
  { id: 'cormallen', name: 'Field of Cormallen', x: 834, y: 668, tier: 3, kind: 'landmark', region: 'Ithilien',
    what: 'Green meadows where the victors camped.',
    history: 'After the fall of Sauron the host of the West rested here. Frodo and Sam woke from their long sleep and were honoured before the whole army.' },
  { id: 'henneth', name: 'Henneth Annûn', x: 850, y: 690, tier: 3, kind: 'fortress', region: 'Ithilien',
    what: 'Hidden cave behind a waterfall.',
    history: 'The Window of the Sunset was a secret refuge of Faramir\u2019s Rangers. Frodo and Sam were brought here; Faramir discovered what Frodo carried, refused to take it, and sent them on with food and counsel.' },
  { id: 'druadan', name: 'Drúadan Forest', x: 764, y: 708, tier: 3, kind: 'forest', region: 'Anórien',
    what: 'Woods of the Wild Men.',
    history: 'The Woses, a secretive people of the woods, lived here. Their headman Ghân-buri-Ghân guided the Rohirrim by forgotten paths around the enemy\u2019s lines.' },
  { id: 'minasmorgul', name: 'Minas Morgul', alt: 'Minas Ithil', x: 870, y: 744, tier: 2, kind: 'dark', region: 'Morgul Vale, Ephel Dúath',
    what: 'The Tower of the Moon, captured by the Nazgûl.',
    history: 'Isildur built Minas Ithil as the twin of Minas Anor. The Nazgûl took it in 2002 of the Third Age and it became Minas Morgul, a city of dread glowing with a corpse-light. Frodo and Sam watched its army march out to war as they crept up the stairs above the vale.' },
  { id: 'ciritungol', name: 'Cirith Ungol', x: 889, y: 726, tier: 2, kind: 'dark', region: 'Ephel Dúath',
    what: 'The secret Spider\u2019s Pass into Mordor.',
    history: 'Gollum led Frodo and Sam up the stairs and into the tunnels of the great spider Shelob, hoping she would deliver him the Ring. Shelob stung Frodo; Sam drove her off, took up the Ring and later rescued his master from the Orc-tower at the top of the pass.' },
  { id: 'blackgate', name: 'Black Gate', alt: 'The Morannon', x: 884, y: 618, tier: 1, kind: 'fortress', region: 'Northwest corner of Mordor',
    what: 'Iron gate across the pass into Mordor.',
    history: 'The Morannon barred the gap between the Ash Mountains and the Mountains of Shadow, guarded by the Towers of the Teeth. Frodo and Sam found it impassable and turned south. Later the Captains of the West led a small army here to draw Sauron\u2019s gaze, and in the midst of the battle the Ring was destroyed and Mordor crumbled.' },
  { id: 'deadmarshes', name: 'Dead Marshes', x: 838, y: 600, tier: 2, kind: 'landmark', region: 'Northwest of Mordor',
    what: 'Fens drowned over an ancient battlefield.',
    history: 'The marshes spread over part of the Dagorlad, where Elves and Men fought Sauron at the end of the Second Age. Pale faces and flickering candles seemed to lie in the pools. Gollum guided Frodo and Sam safely through by hidden paths.' },
  { id: 'emynmuil', name: 'Emyn Muil', x: 802, y: 592, tier: 3, kind: 'landmark', region: 'Between Rohan and the Dead Marshes',
    what: 'A maze of sharp grey hills.',
    history: 'Frodo and Sam wandered lost among these cliffs for days after leaving the Fellowship. There they caught Gollum, who had been following them, and made him swear to guide them.' },
  { id: 'argonath', name: 'Argonath', alt: 'Pillars of the Kings', x: 769, y: 591, tier: 2, kind: 'landmark', region: 'Northern border of Gondor',
    what: 'Two colossal statues flanking the Anduin.',
    history: 'Immense carvings of Isildur and Anárion, each with a hand raised in warning, guard the river at the old northern border of Gondor. The Fellowship\u2019s boats swept between them, and Aragorn stood tall in the stern as their heir.' },
  { id: 'amonhen', name: 'Amon Hen & Parth Galen', x: 762, y: 615, tier: 2, kind: 'landmark', region: 'West shore of Nen Hithoel',
    what: 'The Hill of Sight above a green lakeside lawn.',
    history: 'Here the Fellowship was broken. Boromir tried to take the Ring, and Frodo, invisible, fled up to the seat of Amon Hen, where he felt the Eye seeking him. Frodo slipped away east with Sam, Merry and Pippin were captured, and Boromir died defending them.' },
  { id: 'rauros', name: 'Falls of Rauros', x: 776, y: 631, tier: 3, kind: 'landmark', region: 'Anduin',
    what: 'Thundering falls below Nen Hithoel.',
    history: 'Aragorn, Legolas and Gimli laid Boromir in an elven boat and sent it over the falls. His cloven horn was later found in the river and brought to his father in Minas Tirith.' },
  { id: 'mountdoom', name: 'Mount Doom', alt: 'Orodruin', x: 955, y: 718, tier: 1, kind: 'dark', region: 'Mordor · Gorgoroth',
    what: 'The volcano where the One Ring was made and unmade.',
    history: 'Sauron forged the One Ring in the Chambers of Fire inside this mountain, and only there could it be destroyed. Frodo and Sam crawled up its slopes, Sam carrying his master at the last. At the brink Frodo claimed the Ring for himself, but Gollum bit it from his finger and fell with it into the fire.' },
  { id: 'baraddur', name: 'Barad-dûr', alt: 'The Dark Tower', x: 1010, y: 664, tier: 1, kind: 'dark', region: 'Mordor',
    what: 'Sauron\u2019s immense fortress.',
    history: 'Sauron raised the Dark Tower with the power of the Ring in the Second Age. It was thrown down after the Last Alliance but rebuilt on its old foundations when he returned. When the Ring went into the fire, the tower crumbled into ruin.' },
  { id: 'dunland', name: 'Dunland', x: 528, y: 522, tier: 3, kind: 'realm', region: 'West of the Misty Mountains',
    what: 'Hill-country of the Dunlendings.',
    history: 'The Dunlendings held a long grudge against the Rohirrim, who had settled lands they considered theirs. Saruman exploited that bitterness and sent them against Helm\u2019s Deep; after the battle they were allowed to go home.' },
  { id: 'umbar', name: 'Umbar', x: 800, y: 1118, tier: 2, kind: 'city', region: 'Coast of Harad',
    what: 'Great southern haven of the Corsairs.',
    history: 'Umbar was once a mighty harbour of Númenor. In the Third Age it became the lair of the Corsairs, enemies of Gondor and allies of Sauron, who raided the southern coasts. Serving Gondor in disguise as Thorongil, Aragorn once led a surprise raid that burned much of their fleet.' }
];
